$ANSIBLE_VAULT;1.1;AES256
38393832623438636462336434353965353733376139353666653838313766633861306233326665
3665346166613038366465393361303233363834363561340a356431363764633235393864643264
33653538643034636534626464646131643038373039333631633066363136396439383436343537
6537313730356135630a353534306165376164633533336435373134393632616632333266666534
63326236623234383130346537343466346665633563373831366231336435623931376232663935
63313330656639346236376636316334316535303631303038373830343337663235363231363931
65623430313662343965613964346365376563316339333433666335386465373064386234303636
37316538396238653739663631336666653138646366316135663634353734386237623132343137
34616433643430613566303330323663623733663365666364656236663231663639646166363639
38323535633431316439333137643134346430653436373730653365646139663162393538346161
65326662333566636538313563383239663965323838613037623933643363396639353533323666
66373664353763303334333439343836313561326365333466316564636334383934653939353638
64306631646334616631306363356132653962393532313934363965396338666432636464303231
65396666383865646534353864353931653939326630643030643231663338393561313966323363
31343130666335313064356437346161313461373861363062663739633939643832323034336165
37316538646539376264643833616464336133613330353238396464653938303032373530303335
64326331643165613836666564663635353763306630396139666365396237636638343039336432
36363631366439646230353631336331626137393135363835333237383435323036313265656535
31666162663664613439363536616462373261316234346264636133346164386433666465613465
30396132633839336137313633346662663635623966363361376436313264386565316563613836
62666634663264343437393435613437663030343532396630653438653262326134396166636134
35653566393634626432623432663637313733333031316532353637303638323834353665373737
32303934343735633038643535663932613530353330373138303766376231633765333237316465
33313165636138646637633030643139326464373136636532626561393133366230373531363439
37323164313336663732636634323336656565313938366464666639376433323764
